Repository kakao-tech-campus-2nd-step3/Team16_BE, pull requests merged in 2024-11, with the labels that each got.

#46 [FEAT, REFACTOR, TEST] RedisTemplate 관련 수정, 테스트 코드 수정, 모임만의 개인 일정 생성 추가, Swagger 추가, Dockerfile, docker-compose.yml, nginx.conf 추가, PersonalCalendar 엔티티 관련 코드 삭제
  Dockerfile
  build.gradle
  docker-compose.yml
  nginx.conf
  src/main/java/org/cookieandkakao/babting/common/apiresponse/ApiResponseGenerator.java
  src/main/java/org/cookieandkakao/babting/common/cache/CacheKeyGenerator.java
  src/main/java/org/cookieandkakao/babting/common/cache/RedisConfig.java
  src/main/java/org/cookieandkakao/babting/common/config/OpenApiConfig.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/Event.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/PersonalCalendar.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/repository/PersonalCalendarRepository.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/EventService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingJoinCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingTimeCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MeetingEvent.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/EventTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/PersonalCalendarTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/ReminderTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/EventServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarServiceTest.java
Labels: FEAT, REFACTOR, TEST

#48 [FEAT, REFACTOR] 토큰 재발급 기능 추가, 카카오 토큰 관련 기능 리펙토링
  src/main/java/org/cookieandkakao/babting/common/annotaion/LoginMemberId.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/AuthController.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/MemberController.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/KakaoToken.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/KakaoAuthClient.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/MemberService.java
  src/main/java/org/cookieandkakao/babting/domain/member/util/JwtUtil.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/KakaoTokenTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/MemberTest.java
Labels: FEAT, REFACTOR, TEST

#49 [FEAT] swagger 추가
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodCategoryController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
Labels: FEAT

#47 [FEAT] swagger 추가, api 추가
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingHostCheckResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingInfoGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/TimeAvailableGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
Labels: FEAT, FIX

#50 Week9
  Dockerfile
  build.gradle
  docker-compose.yml
  nginx.conf
  src/main/java/org/cookieandkakao/babting/common/annotaion/LoginMemberId.java
  src/main/java/org/cookieandkakao/babting/common/apiresponse/ApiResponseGenerator.java
  src/main/java/org/cookieandkakao/babting/common/cache/CacheKeyGenerator.java
  src/main/java/org/cookieandkakao/babting/common/cache/RedisConfig.java
  src/main/java/org/cookieandkakao/babting/common/config/OpenApiConfig.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/Event.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/PersonalCalendar.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/repository/PersonalCalendarRepository.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/EventService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodCategoryController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingJoinCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingTimeCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingHostCheckResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingInfoGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/TimeAvailableGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MeetingEvent.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/AuthController.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/MemberController.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/KakaoToken.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/KakaoAuthClient.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/MemberService.java
  src/main/java/org/cookieandkakao/babting/domain/member/util/JwtUtil.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/EventTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/PersonalCalendarTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/ReminderTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/EventServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/KakaoTokenTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/MemberTest.java
Labels: FEAT, REFACTOR, FIX, TEST

#52 week9 코드 review
  Dockerfile
  README.md
  build.gradle
  docker-compose.yml
  nginx.conf
  src/main/java/org/cookieandkakao/babting/common/annotaion/LoginMemberId.java
  src/main/java/org/cookieandkakao/babting/common/apiresponse/ApiResponseGenerator.java
  src/main/java/org/cookieandkakao/babting/common/cache/CacheKeyGenerator.java
  src/main/java/org/cookieandkakao/babting/common/cache/RedisConfig.java
  src/main/java/org/cookieandkakao/babting/common/config/OpenApiConfig.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/Event.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/PersonalCalendar.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/repository/PersonalCalendarRepository.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/EventService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodCategoryController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingJoinCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingTimeCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingHostCheckResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingInfoGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/TimeAvailableGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MeetingEvent.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/AuthController.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/MemberController.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/KakaoToken.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/KakaoAuthClient.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/MemberService.java
  src/main/java/org/cookieandkakao/babting/domain/member/util/JwtUtil.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/EventTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/PersonalCalendarTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/ReminderTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/EventServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/KakaoTokenTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/MemberTest.java
Labels: FEAT, REFACTOR, DOCS, TEST

#54 [TEST] 테스트코드 작성
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodCategoryController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/entity/FoodCategory.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingRecommendedFoodService.java
  src/test/java/org/cookieandkakao/babting/domain/food/FoodCategoryServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/FoodRepositoryServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/MeetingNonPreferenceFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/MeetingPreferenceFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/NonPreferenceFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/PreferenceFoodServiceTest.java
Labels: TEST

#56 [REFACTOR, TEST] RestClient 관련 테스트 작성, 커스텀 예외 적용
  src/main/java/org/cookieandkakao/babting/common/exception/GlobalExceptionHandler.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/ExpiredTokenException.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/MemberController.java
  src/main/java/org/cookieandkakao/babting/domain/member/dto/MemberProfileGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/KakaoAuthClient.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/MemberService.java
  src/main/java/org/cookieandkakao/babting/domain/member/util/JwtUtil.java
  src/test/java/org/cookieandkakao/babting/domain/member/service/KakaoAuthClientTest.java
Labels: REFACTOR, TEST

#62 [FIX] 로그인 결과 redirect url 수정
  src/main/java/org/cookieandkakao/babting/domain/member/controller/AuthController.java
Labels: FIX

#64 [TEST] 컨트롤러 테스트 생성, 서비스 테스트 추가
  src/test/java/org/cookieandkakao/babting/domain/food/controller/FoodCategoryControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/controller/FoodControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/FoodCategoryServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/FoodRepositoryServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdaterTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/MeetingNonPreferenceFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/MeetingRecommendedFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/food/service/PreferenceFoodServiceTest.java
Labels: TEST

#68 [HOTFIX] fix(application.properties): ddl-auto validate -> update
  src/main/resources/application.properties
Labels: FIX

#69 [HOTFIX] meeting event dto 수정
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/dto/PersonalPreferenceUpdateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventDeleteService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingPersonalInfoUpdateService.java
Labels: FIX

#72 docs(LICENSES): 라이센스 추가
  LICENSES/LICENSE.APACHE-2.0
  LICENSES/LICENSE.BSD-2
  LICENSES/LICENSE.EPL-2.0
  LICENSES/LICENSE.GPLv2-Classpath-Exception
  LICENSES/LICENSE.MIT
  LICENSES/LICENSE.OFL
Labels: DOCS

#73 [HOTFIX] 모임의 빈 시간 계산 로직 수정
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingTimeCalculationService.java
Labels: FIX

#74 [FEAT] 수정 사항 반영
  LICENSES/LICENSE.APACHE-2.0
  LICENSES/LICENSE.BSD-2
  LICENSES/LICENSE.EPL-2.0
  LICENSES/LICENSE.GPLv2-Classpath-Exception
  LICENSES/LICENSE.MIT
  LICENSES/LICENSE.OFL
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingTimeCalculationService.java
Labels: FEAT, DOCS, FIX

#75 [HOTFIX] 순환참조 해결
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
Labels: FIX

#76 [HOTFIX] 순환참조 해결
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
Labels: FIX

#80 [FEAT, TEST, FIX] 테스트 코드 수정, 오류 해결 및 데이터 파싱 오류 해결
  src/main/java/org/cookieandkakao/babting/common/util/TimeFormatterUtil.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventDeleteService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingTimeCalculationService.java
  src/test/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventDeleteServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/meeting/service/MeetingPersonalInfoUpdateServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/meeting/service/MeetingTimeCalculationServiceTest.java
  src/test/resources/application-test.properties
Labels: FEAT, REFACTOR, FIX, TEST

#81 [FEAT] Swagger https 연결 설정
  src/main/java/org/cookieandkakao/babting/common/config/OpenApiConfig.java
Labels: FEAT

#82 [FIX] LocalTime에 @JsonFormat(pattern = "HH:mm:ss") 추가
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingUpdateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingInfoGetResponse.java
Labels: FIX

#85 [FEAT] 모임 정보 조회 때 id도 반환하도록 추가
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
Labels: FEAT

#87 [FIX] 버전 동일하게 변경
  src/main/resources/application.properties
Labels: FIX

#88 [REFACTOR] 확정된 음식이 없을 때 null 값 보내게 변경
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingGetResponse.java
  src/main/resources/application.properties
Labels: REFACTOR, FIX

#94 [FIX] Develop 최신화
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingConfirmedInfoResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingTimeCalculationService.java
  src/main/resources/application.properties
  src/test/java/org/cookieandkakao/babting/domain/meeting/service/MeetingTimeCalculationServiceTest.java
Labels: FIX

#101 [FIX] LocalDateTime -> ZonedDateTime 형식으로 변경
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/TimeGetResponse.java
Labels: FIX

#102 [FIX] 최신 상황 반영
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventDeleteService.java
  src/test/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventDeleteServiceTest.java
Labels: FIX

#79 [TEST] 회원기능 관련 테스트 작성
  src/test/java/org/cookieandkakao/babting/domain/member/controller/AuthControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/controller/MemberControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/KakaoTokenTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/entity/MemberTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/service/AuthServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/service/KakaoAuthClientTest.java
  src/test/java/org/cookieandkakao/babting/domain/member/service/MemberServiceTest.java
Labels: TEST

#108 [FIX] 최신 상황 반영
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MeetingEvent.java
Labels: FIX

#109 [FIX] cascade remove 추가
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MemberMeeting.java
Labels: FIX

#110 [FIX] 최신 코드 반영
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
Labels: FIX
