Repository kakao-tech-campus-2nd-step3/Team16_BE, pull requests merged in 2024-10, with the labels that each got.

#22 [FEAT] 톡 캘린더 일정 상세 조회 구현 및 캐시 사용
  build.gradle
  src/main/java/org/cookieandkakao/babting/BabtingApplication.java
  src/main/java/org/cookieandkakao/babting/common/cache/RedisConfig.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/EventCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/EventCreateRequestDto.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/TimeCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventCreateResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventDetailGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventListGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/TimeGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/EventService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarService.java
  src/main/resources/application.properties
Labels: FEAT

#27 [FEAT] 로그인 기능 완성
  src/main/java/org/cookieandkakao/babting/common/annotaion/LoginMemberId.java
  src/main/java/org/cookieandkakao/babting/common/config/WebConfig.java
  src/main/java/org/cookieandkakao/babting/common/resolver/LoginMemberIdArgumentResolver.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/AuthController.java
  src/main/java/org/cookieandkakao/babting/domain/member/dto/KakaoMemberInfoGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/member/dto/KakaoMemberInfoGetResponseDto.java
  src/main/java/org/cookieandkakao/babting/domain/member/dto/KakaoMemberProfileGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/member/dto/KakaoTokenGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/member/dto/TokenIssueResponse.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/KakaoToken.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/Member.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/util/JwtUtil.java
Labels: FEAT

#26 [FEAT] MeetingController 추가
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/ConfirmDateTimeGetRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/LocationCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/LocationGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
Labels: FEAT

#33 [FEAT] 모임별 선호/비선호 음식 CRUD 구현
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/dto/PersonalPreferenceUpdateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/food/entity/MeetingNonPreferenceFood.java
  src/main/java/org/cookieandkakao/babting/domain/food/entity/MeetingPreferenceFood.java
  src/main/java/org/cookieandkakao/babting/domain/food/entity/NonPreferenceFood.java
  src/main/java/org/cookieandkakao/babting/domain/food/entity/PreferenceFood.java
  src/main/java/org/cookieandkakao/babting/domain/food/repository/MeetingNonPreferenceFoodRepository.java
  src/main/java/org/cookieandkakao/babting/domain/food/repository/MeetingPreferenceFoodRepository.java
  src/main/java/org/cookieandkakao/babting/domain/food/repository/NonPreferenceFoodRepository.java
  src/main/java/org/cookieandkakao/babting/domain/food/repository/PreferenceFoodRepository.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodCategoryService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodPreferenceStrategy.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodRepositoryService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceStrategy.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingNonPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/PreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
  src/main/resources/application.properties
Labels: FEAT

#34 [FEAT] 모임 기능 구현
  src/main/java/org/cookieandkakao/babting/domain/food/dto/FoodGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/ConfirmMeetingGetRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/LocationGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/response/MeetingGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Location.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MeetingEvent.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/MemberMeeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MeetingEventRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
Labels: FEAT, REFACTOR

#40 [FEAT] 회원 탈퇴 기능 추가
  src/main/java/org/cookieandkakao/babting/common/properties/KakaoProviderProperties.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/MemberController.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/Member.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/MemberService.java
Labels: FEAT, FIX

#41 [REFACTOR] 쿼리 최적화, 모임별 추천 음식 계산 로직 변경 등
  src/main/java/org/cookieandkakao/babting/common/exception/GlobalExceptionHandler.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/FoodNotFoundException.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/InvalidFoodPreferenceTypeException.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/PreferenceConflictException.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/dto/FoodPreferenceGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodRepositoryService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceStrategy.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingNonPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/PreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
Labels: REFACTOR

#38 [FEAT] RestClientConfig 추가, 테스트 코드 추가 및 수정, 모임 확정 시 캘린더에 일정 추가 부분 수정
  src/main/java/org/cookieandkakao/babting/common/cache/RedisConfig.java
  src/main/java/org/cookieandkakao/babting/common/config/RestClientConfig.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/EventCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/TimeCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventCreateResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/TimeGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/Reminder.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/EventService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingEventCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/ReminderTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/EventServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarServiceTest.java
Labels: FEAT, TEST

#39 [FEAT, REFACTOR] 모임 과 모임 일정 서비스 분리, 빈 시간대 조회 로직 추가, 기타 코드들 수정
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
Labels: FEAT, REFACTOR

#43 Week7,8
  src/main/java/org/cookieandkakao/babting/common/cache/RedisConfig.java
  src/main/java/org/cookieandkakao/babting/common/config/RestClientConfig.java
  src/main/java/org/cookieandkakao/babting/common/exception/GlobalExceptionHandler.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/FoodNotFoundException.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/InvalidFoodPreferenceTypeException.java
  src/main/java/org/cookieandkakao/babting/common/exception/customexception/PreferenceConflictException.java
  src/main/java/org/cookieandkakao/babting/common/properties/KakaoProviderProperties.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarController.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/EventCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/request/TimeCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventCreateResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/EventGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/dto/response/TimeGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/entity/Reminder.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/EventService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientService.java
  src/main/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarService.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/FoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/controller/MemberMeetingFoodPreferenceController.java
  src/main/java/org/cookieandkakao/babting/domain/food/dto/FoodPreferenceGetResponse.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodRepositoryService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/FoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceStrategy.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingFoodPreferenceUpdater.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingNonPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/MeetingPreferenceService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/NonPreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/food/service/PreferenceFoodService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/controller/MeetingController.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/dto/request/MeetingEventCreateRequest.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/entity/Meeting.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/repository/MemberMeetingRepository.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingEventService.java
  src/main/java/org/cookieandkakao/babting/domain/meeting/service/MeetingService.java
  src/main/java/org/cookieandkakao/babting/domain/member/controller/MemberController.java
  src/main/java/org/cookieandkakao/babting/domain/member/entity/Member.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/AuthService.java
  src/main/java/org/cookieandkakao/babting/domain/member/service/MemberService.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/controller/TalkCalendarControllerTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/entity/ReminderTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/EventServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/PersonalCalendarServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarClientServiceTest.java
  src/test/java/org/cookieandkakao/babting/domain/calendar/service/TalkCalendarServiceTest.java
Labels: FEAT, REFACTOR, TEST
